package com.cpad.dao;

public class DbStatements {

    public static class INSERT {
        public static final String APPOINTMENT_DETAILS = "INSERT INTO APPOINTMENT_DETAILS (PATIENT_NAME,EMAIL_ADDRESS,PHONE_NUMBER,AGE,GENDER,PATIENT_CITY,PATIENT_STATE,TYPEOFILLNESS,SYMPTOMS,DESCRIPTION,APPOINTMENTDATE,APPOINTMENTTIME,MODEOFAPPOINTMENT,MEDICALHISTORY) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

    }

    public static class SELECT {
        public static final String FETCH_APPOINTMENT_DETAILS = "SELECT PATIENT_NAME,EMAIL_ADDRESS,PHONE_NUMBER,AGE,GENDER,PATIENT_CITY,PATIENT_STATE,TYPEOFILLNESS,SYMPTOMS,DESCRIPTION,APPOINTMENTDATE,APPOINTMENTTIME,MODEOFAPPOINTMENT,MEDICALHISTORY FROM APPOINTMENT_DETAILS";
    }
}
